== A Divisão de Um Número por Outro

Considere a divisão que está realizada na _continha_ <<tab-1por7>>, abaixo. É assim que aprendemos a fazê-la desde as primeiras séries escolares. Este é o procedimento simples com o qual dividimos qualquer número latexmath:[\large n] por um outro número latexmath:[\large d]. Ele é o nosso ponto de partida.

:table-caption!:
:tab1: 1 dividido por 7
[.center.division-style,frame="ends" grid="none", width=25]
.{tab1}.
[cols="2,4"]
[[tab-1por7, {tab1}]]
|===
| 1 | [#division-symbol]*7{sp}*

| [.barra-conta]*-0*
| 0,142857

| 10
| 

| [.barra-conta]*-7*
| 

| 30
| 

| [.barra-conta]*-28*
| 
|20
|

|[.barra-conta]*-14*
|

|60
|

|[.barra-conta]*-56*
|

|40
|

|[.barra-conta]*-35*
|

|50
|

|[.barra-conta]*-49*
|

|1
|
|===
:table-caption:

Por ora, vamos apenas observar que, em <<tab-1por7>>, paramos de calcular quando obtivemos o número latexmath:[\large 1], que é o numerador com o qual iniciamos a conta.

Agora, é preciso que reconheçamos que, na continha acima, fizemos os seguintes cálculos

// :equ: {counter: eq}
// [[eq-1por7-continhas-1, {equ} ]]
[latexmath#eq-1por7-continhas-1, reftext={counter: eq}]
++++
\large
\begin{equation}
\begin{matrix}
1-7\cdot 0=1\\
10-7\cdot 1 = 3 \\
30-7\cdot 4 = 2 \\
20-7\cdot 2 = 6 \\
60-7\cdot 8 = 4 \\
40-7\cdot 5 = 5 \\
50-7\cdot 7 = 1 
\end{matrix}
\end{equation}
++++
// ({equ})

Se for preciso, o leitor deve fazer à mão a divisão de 1 por 7, ou de quaisquer pares de números, para se convencer (e relembrar) do que acabamos de ver.

Vamos agora, fazer uma pequena manipulação em cada uma das equações acima, trocando de lado o segundo termo do membro esquerdo com o número do membro direito.

// :equ: {counter: eq}
// [[eq-1por7-continhas-2,({equ}) ]]
[latexmath#eq-1por7-continhas-2, reftext={counter: eq}]
++++
\large
\begin{equation}
\begin{matrix}
1-1=7\cdot 0\\
10-3 = 7\cdot 1  \\
30-2 = 7\cdot 4  \\
20-6 = 7\cdot 2  \\
60-4 = 7\cdot 8  \\
40-5 = 7\cdot 5  \\
50-1 = 7\cdot 7
\end{matrix}
\end{equation}
++++
// ({equ})


Agora, daremos um "_pulo de gato_" e traduziremos as 8 equações acima em congruências matemáticas. Esta transposição simples de linguagem nos dotará das possibilidades algébricas operativas e expressivas que usaremos em todo este trabalho. Esta tradução deixa as 8 equações acima com o seguinte aspecto:

// :equ: {counter: eq}
// [[eq-congruencias,({equ}) ]]
[latexmath#eq-congruencias, reftext={counter: eq}]
++++
\large
\begin{equation}
\begin{matrix}
1\equiv 1 (mod\ 7) \\
10\equiv 3 (mod\ 7) \\
30\equiv 2 (mod\ 7) \\
20\equiv 6 (mod\ 7)\\
60\equiv 4 (mod\ 7) \\
40\equiv 5 (mod\ 7) \\
50\equiv 1 (mod\ 7) 
\end{matrix}
\end{equation}
++++
// ({equ})

Bem, agora, vamos mostrar a forma geral da _continha_ usada para dividir um número latexmath:[\Large n] por outro número latexmath:[\Large d]. A continha <<tab-1por7>> acima é um caso particular do que vamos expor abaixo.

:table-caption!:
:tab2: n dividido por d
[.center.division-style,frame="ends" grid="none", width=30]
.{tab2}.
[cols="2,4"]
[[tab-npord, {tab2}]]
|===
| n | [#division-symbol]*d{sp}*

| [.barra-conta]*latexmath:[-d\cdot a_0]*
| latexmath:[a_0,a_1a_2a_3\dots a_{\alpha}]

| latexmath:[10\cdot r_0]
| 

| [.barra-conta]*latexmath:[-d\cdot a_1]*
| 

| latexmath:[10\cdot r_1]
| 

| [.barra-conta]*latexmath:[-d\cdot a_2]*
| 
|latexmath:[10\cdot r_2]
|

|[.barra-conta]*latexmath:[-d\cdot a_3]*
|

|latexmath:[10\cdot r_3]
|

|latexmath:[\vdots]
|

|latexmath:[10\cdot r_{\alpha-1}]
|

|[.barra-conta]*latexmath:[-d\cdot a_{\alpha}]*
|

|latexmath:[r_{\alpha}]
|
|===
:table-caption:

Como antes, esta conta pode ser prontamente convertida em

// :equ: {counter: eq}
// [[eq-npord-continhas-1, {equ} ]]
[latexmath#eq-npord-continhas-1, reftext={counter: eq}]
++++
\large
\begin{equation}
\begin{matrix}
n-d\cdot a_0=r_0\\
10\cdot r_0-d\cdot a_0 = r_1\\
10\cdot r_1-d\cdot a_1 = r_2\\
10\cdot r_2-d\cdot a_2 = r_3\\
\vdots\\
10\cdot r_{\alpha-1}-d\cdot a_{\alpha} = r_{\alpha}
\end{matrix}
\end{equation}
++++
// ({equ})

para, então, trocarmos membros de lado e obtermos

// :equ: {counter: eq}
// [[eq-npord-continhas-2, {equ} ]]
[latexmath#eq-npord-continhas-2, reftext={counter: eq}]
++++
\large
\begin{equation}
\begin{matrix}
n-r_0=d\cdot a_0\\
10\cdot r_0-r_1 = d\cdot a_0\\
10\cdot r_1-r_2 = d\cdot a_1\\
10\cdot r_2-r_3 = d\cdot a_2\\
\vdots\\
10\cdot r_{\alpha-1}-r_{\alpha} = d\cdot a_{\alpha}
\end{matrix}
\end{equation}
++++
// ({equ})

e, finalmente, fazermos a conversão de (<<eq-npord-continhas-2>>) para o formato congruencial

// :equ: {counter: eq}
// [[eq-congruencias-2, {equ} ]]
[latexmath#eq-congruencias-2,reftext={counter: eq}]
++++
\large
\begin{equation}
\begin{matrix}
n\equiv r_0(mod\ d)\\
10\cdot r_0\equiv r_1 (mod\ d)\\
10\cdot r_1\equiv r_2 (mod\ d)\\
10\cdot r_2\equiv r_3 (mod\ d)\\
\vdots\\
10\cdot r_{\alpha-1}\equiv r_{\alpha} (mod\ d)
\end{matrix}
\end{equation}
++++
// ({equ})

É neste ponto que queríamos chegar! A partir daqui, a Teoria Alpha se desenrola!

Veremos, em seguida, que a expressão em <<eq-congruencias-2>> é prontamente generalizada para um base latexmath:[\large b] qualquer, de modo que a sua aparência fica

// :equ: {counter: eq}
// [[eq-mad, {equ} ]]
[latexmath#eq-mad, reftext={counter: eq}]
++++
\large
\begin{equation}
\begin{matrix}
n\equiv r_0(mod\ d)\\
b\cdot r_0\equiv r_1 (mod\ d)\\
b\cdot r_1\equiv r_2 (mod\ d)\\
b\cdot r_2\equiv r_3 (mod\ d)\\
\vdots\\
b\cdot r_{\alpha-1}\equiv r_{\alpha} (mod\ d)
\end{matrix}
\end{equation}
++++
// ({equ})

Já quero adiantar que as expressões em <<eq-congruencias-2>> e em <<eq-mad>> permitem a contagem do número de algarismos periódicos da dízima de latexmath:[\Large \frac{n}{d}] e que isto acontece, basicamente, porque latexmath:[\Large r_0=r_{\alpha}]. Há outros detalhes envolvidos nesta última e pequena equação. Veremos todos eles, por completo, no que se seguirá.

Por fim, observemos que <<eq-mad>> tem, em si, uma sequência finita, latexmath:[\large s], de inteiros positivos. Estes inteiros positivos são os restos, latexmath:[\large r_i], que aparecem na divisão de latexmath:[\large n] por latexmath:[\large d]. Assim, latexmath:[\large s=\{r_i\}_{i=0}^{\alpha}]. A Teoria Alfa tem tudo a ver com a contagem dos elementos de latexmath:[\large s] e com a tentativa de divisar as suas belas e frutuosas propriedades matemáticas.

// === Exercícios

// . Utilize os campos abaixo para informar numeradores (n) e denominadores (d) para calcular e exibir, automaticamente, os restos e os algarismos da divisão latexmath:[\large \frac{n}{d}].

// ++++
// Numerador: <input class="numerador" type="text" name="quantidade" min="1" required>
// <br>
// Denominador: <input class="denominador" type="text" name="quantidade" min="1" required>
// <br>
// Base: <input class="base" type="text" name="quantidade" value="10" min="1" required>
// <br>
// <button class="calcular">Calcular</button>
// <div class="result"></div>
// ++++

// ++++
// Numerador: <input id="numerador" type="number" name="quantidade" min="1" required>
// <br>
// Denominador: <input id="denominador" type="number" name="quantidade" min="1" required>
// <br>
// Base: <input id="base" type="number" name="quantidade" value="10" min="1" required>
// <br>
// <button id="calcular">Calcular</button>
// <div id="result"></div>
// ++++
