[preface]
== Prefácio

//Quando dividimos um número por outro, o resultado é expresso em uma sequência de algarismos. Esta sequência de algarismos tem uma parte fracionária, que são aqueles algarismos que vêm depois da vírgula. Esta parte fracionária tem, ela própria, duas porções que não ficam especialmente destacadas uma da outra: uma que sempre está ali e outra que só às vezes aparece.

É possível calcular o número de algarismos que há na dízima de qualquer número racional.
Sempre há uma sequência de algarismos que se repetem e, às vezes, aparece uma outra sequência que ocorre uma única vez. Podemos calcular o número de algarismos de ambas!

Por exemplo, a dízima de latexmath:[\Large \frac{1}{7}=0,142857...] tem 6 algarismos que se repetem indefinidamente, na mesma ordem, latexmath:[142857], e formam assim a dízima infinita do número latexmath:[\Large \frac{1}{7}].

Um outro exemplo é o da fração latexmath:[\Large \frac{8}{65}=0,123076923...]. A sequência inicial, latexmath:[\Large 123], de três algarismos, ocorre uma única vez. Após este período inicial, a dízima do latexmath:[\Large \frac{8}{65}] compõe-se apenas da sequencia latexmath:[\Large 076923].

Foi observando números assim, que, muitos anos atrás, eu quis encontrar a fórmula que dava a exata quantidade de algarismos no período de qualquer número que tivesse a forma latexmath:[\Large \frac{1}{n}].

Os primeiros _insights_ sobre como chegar em tal fórmula ocorreram aos poucos, demoradamente.

No meio-tempo, eu calculei, calculei e calculei... Hoje em dia, percebo que, naquela época, eu passava longos períodos em uma atitude de extrema concentração que não era completamente palatável para familiares, amigos e pessoas mais próximas. Mas, embora, o aspecto social da minha vida naquele tempo tenha ficado abaixo das minhas próprias expectativas, este fato, foi, eventualmente, compensado por pequenas descobertas e pela beleza e verdade de certas equações, fruto de um trabalho que nunca me negou gozos e satisfações de tempos em tempos.

Eu realmente passava, muitas vezes, horas, dias e noites tentando conjurar verdades matemáticas a partir de pensamentos e esquemas mentais que, à época, ainda estavam pouco ou nada equipados com os instrumentos próprios da arte. Não que hoje em dia eu esteja muito melhor do que naquela época, mas, saber que a Realidade existe em Deus, que abstrações matemáticas vão daquela em direção a Este e que não passam de abstrações se restritas a formalismos lógico-analíticos excessivos, sem o batismo nas águas profundas da poesia até os mares abertos da dialética, repito, saber disto robustece a inteligência, pois enche o pensamento daqueles extratos da realidade que vão desde o mais material e grosseiro até às intangibilidades abissais do Verbo e, para além, no Espírito.

Eu eventualmente cheguei às tais fórmulas que eu procurava. Obtive, primeiro, a fórmula para o período que se repete, ou, período verdadeiro, e a chamei de latexmath:[\Large \alpha] (letra grega alfa). Quando, finalmente, cheguei à fórmula daquele primeiro período, aquele que nem sempre ocorre, o falso período, chamei-o de latexmath:[\Large \widetilde{\alpha}] (lê-se alfa til). Eu, pessoalmente, chamo todo este trabalho de _Teoria Alfa_. O desenvolvimento da teoria está longe de ser acabado, muito mais longe do que o seu início até o momento em que escrevo! Mas, cada vez que a retomo, a retomo porque uma nova intuição se deixa perceber e, normalmente, traz consigo a ponta de linha de um novelo muito longo.

Posteriormente, avancei ainda um pouco mais e cheguei a uma fórmula para latexmath:[\Large \alpha(b,m,n)] e latexmath:[\Large \widetilde{\alpha}(b,m,n)], que dão o número de algarismos no período e no falso período dizimais de um racional qualquer, latexmath:[\Large \frac{m}{n}], e em uma base latexmath:[\large b] qualquer. Mas, o tema deste primeiro livro é a fórmula do número de algarismos do período falso e o caminho que leva até ela.

O leitor verá que a teoria se desenvolve a partir de uma formalização inicial do procedimento simples que realiza a divisão de latexmath:[\large m] por latexmath:[\large n] para, a partir do segundo volume, uma algebrização que relaciona latexmath:[\large \alpha] com outras quantidades e entes que surgem naturalmente durante este processo de contagem de algarismos, e, de repente, saltaremos para um campo aberto em que os próprios números inteiros serão dados em forma algébrica em termos dos latexmath:[\large \alpha]`s envolvidos em sua fatoração prima. É um caminho longo em que beleza e admiração vão se intensificando e mais que compensando o esforço da caminhada.

O leitor verá também que os números latexmath:[\Large \alpha] ou latexmath:[\Large \widetilde{\alpha}] não são tão importantes em si mesmos. É que eles mudam de base para base. Explicarei isto em grande detalhe, neste presente volume e no próximo. Mas, a tentativa de enquadrá-los em fórmulas é tão frutífera, bela e nutritiva, pois que leva à matematização da própria maneira de se escrever um número racional, em uma base qualquer, e a fortalecer a evidência que nos leva a definir os números reais como sendo, ao mesmo tempo, *_a característica gregária e unitária do todo e de suas partes_*, que é, de fato, um aspecto de tudo o que é objeto de experiência.

// No momento em que redijo esta introdução, um grande número de teoremas, lemas, corolários e definições estão já provados. Contudo, é preciso dar a eles o contexto verbal adequado. Deste modo, irei postando os artigos à medida em que os for preparando. A matemática envolvida lida com conceitos simples e fáceis de serem apreendidos e qualquer pessoa com muito boa vontade para com ele pode entender perfeitamente bem o assunto.

//Até o momento, um grande número de teoremas, lemas, corolários e definições estão já provados e muitos outros à caminho de o serem. Contudo, é preciso dar a eles o contexto verbal adequado para pô-los em livro. Deste modo, irei publicando novos volumes à medida em que os for aprontando.

A matemática usada na apresentação desta teoria, lida com conceitos simples e fáceis de serem apreendidos e qualquer pessoa com muito boa vontade para com eles pode entender perfeitamente bem o assunto. Logo, logo, iniciarei a publicação de vídeos em meu canal de YouTube (@aprodriguesOficial) para dar maiores explicações sobre alguns pontos apresentados neste livro e para apresentar alguns dos conceitos-chave que servem de base à teoria alfa.

Este volume apresenta os rudimentos da teoria alfa e termina com a exposição da fórmula de latexmath:[\Large \widetilde{\alpha}] e, pelo menos, uma de suas aplicações interessantes. Tudo o que virmos aqui, servirá de base ao conteúdo do próximo livro que, na opinião deste autor, é a parte principal e mais interessante da teoria alfa.

Como uma palavra final deste prefácio, eu gostaria de dizer que o assunto apresentado, aqui, decorre de um interesse que jamais dependeu de notas, de salário, ou de compensações financeiras, embora estes últimos dois tenham feito falta e teriam sido muito bem-vindos. Eu apenas tentei resolver um problema tal como ele se apresentou a mim e tenho sido bem-sucedido nisto. Certamente, não sou o primeiro a falar sobre estas coisas, nem serei o último. Não tenho a intenção de estar afinado com o que estão dizendo ou fazendo na academia, embora não despreze nada daquilo.

Em se tratando de vida de estudos, tento seguir as indicações dadas pelos meus interesses mais pessoais ou as dadas pelas necessidades apontadas por aquilo que eu esteja estudando em dado momento. Com certeza, isto não é uma receita que valha para todos. Cada indivíduo com vocação para a vida de estudos deve entender-se, em primeiro lugar, e saber dispor os recursos e oportunidades para este fim de modo que seja o melhor para si. Este autor encara a vida de estudos no tempo presente como uma preparação para a Eternidade na qual, em verdade, já estamos. Então, não há pressa alguma em chegar a algum destino, apenas o compromisso sério em conduzir-me _para fora_ em direção a domínios cada vez maiores da Realidade.

//Deste modo, estes pequenos artigos serão aqui colocados aos poucos como forma de divulgar o que tenho escrito.

//Talvez algum leitor se sinta estimulado a continuá-lo ou, simplesmente, algum interesse pelo assunto ou pela Matemática seja semeado.

////
Deste modo, não tenho mais a pressa em buscar os limites do conhecimento atual, os quais se dilatam constantemente. Este autor dá mais valor à profundidade do que à larguesa e, mesmo assim, aprofunda-se em passos de formiga, despreocupado com o aumento inflacionado da ciência do nosso tempo em que o aumento do conhecimento reflete também o aumento de contradições e fraudes, verdadeiramente científicas.
////

//O mundo físico que percebemos através dos cinco sentidos e que sondamos através da razão está sediado em sua contraparte, para onde a razão também se expande, mas tenuemente, e onde os sentidos já quase não penetram.